// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Canvas: typeof import('./src/components/Pixi/Canvas.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    Main: typeof import('./src/components/main.vue')['default']
    Pixi: typeof import('./src/test/TestMain.vue')['default']
    RightToolBox: typeof import('./src/components/RightToolBox.vue')['default']
    Svg: typeof import('./src/components/Svg.vue')['default']
  }
}
