// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Canvas: typeof import('./src/components/Canvas.vue')['default']
    RightToolBox: typeof import('./src/components/RightToolBox.vue')['default']
  }
}
